name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Publish Lib
      - name: publish lib on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/AmCreations.Configuration.EncryptedJson/AmCreations.Configuration.EncryptedJson.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      # Publish Cli tool
      - name: publish cli tool on version change
        id: publish_nuget_cli
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/AmCreations.Configuration.EncryptedJson.Cli/AmCreations.Configuration.EncryptedJson.Cli.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
